{
  "typemeta": {
    "apiVersion": "kubescheduler.config.k8s.io/v1alpha1",
    "kind": "KubeSchedulerConfiguration"
  },
  "SchedulerName": "default-scheduler",
  "AlgorithmSource": {
    "Provider": "DefaultProvider"
  },
  "HardPodAffinitySymmetricWeight": 1
}
